### ISSUE TITLE
Warning logs interfere with progress spinner rendering

### ISSUE THREAD

**Issue by tetsuo-cpp** [trailofbits/pip-audit#120]
As mentioned in https://github.com/trailofbits/pip-audit/issues/116#issuecomment-964579623, warning logs cause the progress spinner to render incorrectly and take up multiple lines.

Perhaps we can think about saving these warnings and then logging them all after the audit is done and the progress spinner is no longer active.

**Comment by woodruffw** [comment]
It's been a long time since I've looked at anything fancier than basic colors in a terminal, but there _should_ be some way to do this without buffering our warnings until the very end. In particular, there should be a way to pin the spinner to the current terminal row, such that all warnings "fall" out from it.

**Comment by tetsuo-cpp** [comment]
There seems to be functionality to achieve this in `tqdm` and some other progress bar libraries, but not with `progress`.

I'm taking a look at `pip` since I know for sure that they get this right and am hoping that we can copy their approach. I haven't been able to spot where they're doing it but will continue looking tomorrow.

**Comment by tetsuo-cpp** [comment]
Ok, `pip` sidesteps this problem by just not using a spinner when subprocess output is being logged. When using a spinner, `pip` only writes output when it hits an error after the fact (kind of like the buffering approach we discussed).

My current plan is to just buffer the warning messages until the end of the audit. We **could** try to do something like what `tqdm` does but it seems quite error prone and wouldn't be transferable to `pip` since it clashes with their approach. One thing I like about the `tqdm` helper is that it registers a logging handler so the code within can just call `logger.info` without caring about the buffering approach so I'm going to borrow that idea.
