### ISSUE TITLE
Add timeout for network requests

### ISSUE THREAD

**Issue by c00kiemon5ter** [trailofbits/pip-audit#126]
By default, network requests by `requests` do not have a timeout. It is recommended to set a timeout to all such calls.

Reference: https://docs.python-requests.org/en/master/user/advanced/#timeouts

**Comment by woodruffw** [comment]
Thanks. `pip` has the `--timeout` option, so we'll mirror that.

**Comment by woodruffw** [comment]
(ICYMI: please use the new issue template for the next report! It'll be easier to triage as volume increases.)
