### ISSUE TITLE
Whittle down the public APIs

### ISSUE THREAD

**Issue by woodruffw** [trailofbits/pip-audit#130]
For the time being, we want to keep our publicly supported APIs to a bare minimum. In particular, that probably means just the following modules:

* `pip_audit.audit` (the `Auditor` class and `AuditOptions`)
* `pip_audit.service` (vulnerability services and interfaces)
* `pip_audit.dependency_source` (dependency sources and interfaces)

Everything else should be considered API private for the time being, and we should mark it as such. Additionally, some of the things in those public modules should also be marked private (like `resolvelib` helper classes/implementations).

Blocks #129.

**Comment by di** [comment]
We might also want to think about how we can expose a simpler API than what `audit` currently provides, i.e. could we expose something that doesn't require any other part of the API to be exposed?

**Comment by woodruffw** [comment]
Yeah, that's a good idea. We could expose an `audit` function similar to the one in `pip_audit.cli`, with a signature that looks something like:

```python
def audit(deps: Sequence[str]) -> Dict[str, List[T]]:
    ...
```

...where that `T` could just be a `dict-serialized` form of `VulnerabilityResult`, perhaps.
