### ISSUE TITLE
Unexpected behaviour when using the --cache-dir argument

### ISSUE THREAD

**Issue by westonsteimel** [trailofbits/pip-audit#131]
## Bug description

When using `pip-audit` with the `--cache-dir` argument, it uses only the last component of the path passed in.  I believe this is because it is using the [name](https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.name) property of the Path object https://github.com/trailofbits/pip-audit/blob/a2449e92dd2684173323407a8fb126ed77d1c5e7/pip_audit/service/pypi.py#L108

## Reproduction steps 

```shell
pip-audit --cache-dir /tmp/pip-audit/
```

You should observe that a `pip-audit` directory has been created in the current working directory rather than at `/tmp/pip-audit`

## Expected behavior

I would expect the cache to be at `/tmp/pip-audit/`

## Platform information

* OS name and version: Debian 11
* `pip-audit` version (`pip-audit -V`): 0.0.6
* Python version (`python -V` or `python3 -V`): 3.9.7
* `pip` version (`pip -V` or `pip3 -V`): 21.2.4

**Comment by tetsuo-cpp** [comment]
Thanks @westonsteimel. I can confirm that this reproduces for me. I have a fix incoming.
