### ISSUE TITLE
Progress spinner: buggy behavior in some terminal emulators

### ISSUE THREAD

**Issue by woodruffw** [trailofbits/pip-audit#135]
I've noticed this behavior in both iTerm and Alacritty on macOS: sometimes `pip-audit`'s spinner will render once per line, rather than sticking to the same line.

Here's the buggy behavior on Alacritty:

[![asciicast](https://asciinema.org/a/446637.svg)](https://asciinema.org/a/446637)

and iTerm 2:

[![asciicast](https://asciinema.org/a/450707.svg)](https://asciinema.org/a/450707)

and here is is working **correctly** in Terminal.app:

[![asciicast](https://asciinema.org/a/450708.svg)](https://asciinema.org/a/450708)

I'm not really sure what's up with this: it only seems to happen when `pip-audit` is used with a requirements source rather than an environmental source, so it might be caused either by something we're printing differently for that source *or* by the slower steps in between actions. Needs debugging.

**Comment by di** [comment]
Looks like this happens when the line to be printed exceeds the width of the terminal:

https://asciinema.org/a/TIkTlhSX63EAFcbhmXf1hhU99

**Comment by woodruffw** [comment]
Thanks for catching that! This looks like the upstream issue: https://github.com/verigak/progress/issues/40
