### ISSUE TITLE
JSONDecodeError exception is raised

### ISSUE THREAD

**Issue by Lewiscowles1986** [trailofbits/pip-audit#155]
## Bug description

Upon following the README.md to install, successfully running given the examples within python projects. When I run outside of a python project; I get an error on a windows system. It's needlessly verbose.

This isn't just about me testing the fences or being obtuse. Sometimes CI and build servers (particularly in mono-repos) need to switch environments and working directories. This would absolutely impact the case for a windows runner in the wrong folder.

## Reproduction steps 

```
python3 -m pip install -U pip-audit
pip-audit
```

## Screenshots and logs

```
$ pip-audit
WARNING: You are using pip version 20.3.1; however, version 21.3.1 is available.
You should consider upgrading via the 'c:\python38amd64\python.exe -m pip install --upgrade pip' command.

←[?25hTraceback (most recent call last):
  File "c:\python38amd64\lib\site-packages\pip_audit\_dependency_source\pip.py", line 64, in collect
    for (_, dist) in pip_api.installed_distributions(local=self._local).items():
  File "c:\python38amd64\lib\site-packages\pip_api\_installed_distributions.py", line 83, in installed_distributions
    return _new_installed_distributions(local)
  File "c:\python38amd64\lib\site-packages\pip_api\_installed_distributions.py", line 71, in _new_installed_distributions
    for raw_dist in json.loads(result):
  File "c:\python38amd64\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "c:\python38amd64\lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 30318)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\python38amd64\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38amd64\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python38amd64\Scripts\pip-audit.exe\__main__.py", line 7, in <module>
  File "c:\python38amd64\lib\site-packages\pip_audit\_cli.py", line 240, in audit
    for (spec, vulns) in auditor.audit(source):
  File "c:\python38amd64\lib\site-packages\pip_audit\_audit.py", line 60, in audit
    yield from self._service.query_all(specs)
  File "c:\python38amd64\lib\site-packages\pip_audit\_service\interface.py", line 115, in query_all
    for spec in specs:
  File "c:\python38amd64\lib\site-packages\pip_audit\_dependency_source\pip.py", line 81, in collect
    raise PipSourceError("failed to list installed distributions") from e
pip_audit._dependency_source.pip.PipSourceError: failed to list installed distributions

```

## Platform information

* OS name and version: Windows 10 64-bit Pro
* `pip-audit` version (`pip-audit -V`): 1.0.0
* Python version (`python -V` or `python3 -V`): 3.8.1 😬 (I'll upgrade that separately)
* `pip` version (`pip -V` or `pip3 -V`): 21.1.2

## Additional context

I Understand I should perhaps use flags.

I expected this to be the default, or for usage to be output if I supply no default command.

* [X] `pip-audit -l` works
* [X] `pip-audit --help` works
* [X] `pip-audit -r /path/to/requirements.txt` works for both existing and non-existing paths

**Comment by Lewiscowles1986** [comment]
Same behavior when using python 3.10.0 with up to date pip 👍

**Comment by tetsuo-cpp** [comment]
@Lewiscowles1986 
Thanks for the bug report and showing interest in `pip-audit`!

> This isn't just about me testing the fences or being obtuse. Sometimes CI and build servers (particularly in mono-repos) need to switch environments and working directories. This would absolutely impact the case for a windows runner in the wrong folder.

Just to clarify, if you run `pip-audit` from a different directory, does the behaviour change? I don't think the working directory should affect much as it just queries the output of `pip list` which you can run from anywhere.

@woodruffw I suspect this is the same as #122 (specifically the stack trace in https://github.com/trailofbits/pip-audit/issues/116#issue-1049107467).

**Comment by Lewiscowles1986** [comment]
The working directory should not matter for `pip-audit -l` or in-fact `pip-audit` (no arguments) in my opinion. That is not the subject of this issue. Operating from a different folder generates the same issue.

**Comment by woodruffw** [comment]
Hmm, that `JSONDecoderError` is fishy — looks similar to #116, which we never fully root caused.

**Comment by di** [comment]
@Lewiscowles1986 Can you give us the output of `pip list -v --format=json` in both a directory where it works and a directory where it doesn't work?

**Comment by Lewiscowles1986** [comment]
Umm.. The output is the same regardless of this working...

```
$ pip list -v --format=json
[{"name": "backports.entry-points-selectable", "version": "1.1.1", "location": "c:\\users\\lewis\\appdata\\roaming\\python\\python310\\site-packages", "installer": "pip"}, {"name": "distlib", "version": "0.3.3", "location": "c:\\users\\lewis\\appdata\\roaming\\python\\python310\\site-packages", "installer": "pip"}, {"name": "filelock", "version": "3.4.0", "location": "c:\\users\\lewis\\appdata\\roaming\\python\\python310\\site-packages", "installer": "pip"}, {"name": "pip", "version": "21.2.3", "location": "c:\\program files\\python310\\lib\\site-packages", "installer": "pip"}, {"name": "platformdirs", "version": "2.4.0", "location": "c:\\users\\lewis\\appdata\\roaming\\python\\python310\\site-packages", "installer": "pip"}, {"name": "setuptools", "version": "57.4.0", "location": "c:\\program files\\python310\\lib\\site-packages", "installer": "pip"}, {"name": "six", "version": "1.16.0", "location": "c:\\users\\lewis\\appdata\\roaming\\python\\python310\\site-packages", "installer": "pip"}, {"name": "virtualenv", "version": "20.10.0", "location": "c:\\users\\lewis\\appdata\\roaming\\python\\python310\\site-packages", "installer": "pip"}]
```

It is for sure a spicy meatball. Unfortunately debugging in windows is awful. And on Linux it works.

**Comment by Lewiscowles1986** [comment]
TBF, I will just avoid using this on windows. That is my fix for myself 😄
