### ISSUE TITLE
fails if package not found on public pypi index

### ISSUE THREAD

**Issue by dhuckins** [trailofbits/pip-audit#165]
## Bug description

when a python package is not found in the public pypi index (pypi.org), raises an unexpected error

## Reproduction steps 

slightly tough to reproduce but maybe you can get an idea to the error via the output
https://gist.github.com/dhuckins/a246c454ee8d89b7441aa35e61f06618

we have a package (`the-package-not-in-pypi` for example) listed in requirements.txt, it is pulled from a private python index (set via extra-index-url)
seems like when this library attempts to resolve `the-package-not-in-pypi`, it fails

(I do see the `strict` flag has a default of `false`, that seems to have no effect here)

## Expected behavior
expected to see listed vulns or "No known vulnerabilities found"

## Screenshots and logs
https://gist.github.com/dhuckins/a246c454ee8d89b7441aa35e61f06618

## Platform information

* OS name and version: Darwin 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64

* `pip-audit` version (`pip-audit -V`): 1.0.0
* Python version (`python -V` or `python3 -V`):  Python 3.9.9
* `pip` version (`pip -V` or `pip3 -V`): 21.2.4

**Comment by dhuckins** [comment]
let me know if you need something truly reproducible (anything not in pypi.org should hypothetically work)

**Comment by di** [comment]
Thanks @dhuckins! This is a duplicate of #157 and was just fixed in #162 (but hasn't been released yet). We'll probably want to cut a new release today with that change.

**Comment by dhuckins** [comment]
> Thanks @dhuckins! This is a duplicate of #157 and was just fixed in #162 (but hasn't been released yet). We'll probably want to cut a new release today with that change.

_sigh_ sorry about that, even searched for the issue before creating/commenting

thanks!

**Comment by dhuckins** [comment]
confirmed it works when installing from git

thanks!
