### ISSUE TITLE
`-m` entry point

### ISSUE THREAD

**Issue by tonybaloney** [trailofbits/pip-audit#167]
I'm trying to configure pip-audit to run automatically for my project.

I have to run pip audit via `python -m pip_audit`, but there is no module entry point.

Please could one be added? IT looks like it would just run `_cli:audit`,

Happy to raise a PR if you agree this is useful.

**Comment by woodruffw** [comment]
Yeah, I think we can do that.

Just out of curiosity: is there a reason why you can't run the `pip-audit` console entrypoint directly?

**Comment by di** [comment]
We should definitely do this, and also encourage using `$ python -m pip-audit` instead of `$ pip-audit` in our docs and examples.

**Comment by tonybaloney** [comment]
> Yeah, I think we can do that.
> 
> Just out of curiosity: is there a reason why you can't run the `pip-audit` console entrypoint directly?

I'm configuring this as a task in VS Code that runs whenever a project is opened, so you have to get the python interpreter from a variable and the venv isn't activated.

`.vscode/tasks.json` will look like this-- 

```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Pip Audit",
            "type": "shell",
            "command": "${command:python.interpreterPath}",
            "args": ["-m", "pip-audit"],
            "isBackground": true,
            "group": "none",
            "runOptions": {
                "runOn": "folderOpen",
            },
        },
    ]
}
```

**Comment by woodruffw** [comment]
@tonybaloney Done with #173!

This should work for you now, assuming you install from GitHub:

```
python -m pip_audit [args...]
```

And we'll cut a release with that soon, as well.
