### ISSUE TITLE
Add a --require-hashes flag

### ISSUE THREAD

**Issue by di** [trailofbits/pip-audit#172]
Similar to `pip`'s [`--require-hashes` flag](https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-require-hashes), when auditing requirements files, `pip-audit` should support a `--require-hashes` flag that:

- requires all auditable dependencies to be pinned and hashed
- disables dependency resolution

Additionally, it would likely be desirable for `pip-audit` to ensure that the hashes that are present match hashes provided via PyPI's JSON API.

**Comment by woodruffw** [comment]
cc @tetsuo-cpp: Let's prioritize this one next.
