### ISSUE TITLE
Can we have a --verbose flag for diagnosing performance problems?

### ISSUE THREAD

**Issue by matthewdeanmartin** [trailofbits/pip-audit#177]
**Is your feature request related to a problem? Please describe.**

`pip-audit` will finish in a few seconds but `pip-audit -r requirement.txt` hangs forever. If I interrupt it, sometimes it is in the middle of trying to upgrade pip, sometimes it is in the middle of trying to POST something via requests (as inferred from the call stack at point of killing the process)

**Describe the solution you'd like**
I'd like `pip-audit` to not hang on windows 10, when using python 3.9, pipenv or pipx, when on corporate VPN, with shell of git-bash or cmd.exe... but I can't send my laptop to y'all to diagnose what's up so I don't really expect a bug report to get any attention.

So I'd like a --verbose flag so I can diagnose what is happening and where the code is hanging (is the company's net-nanny banning the domain of something because it is uncategorized, who knows? is it hitting a free service and getting rate limited? Is it calling `safety` without an API key like pipenv used to?)

**Describe alternatives you've considered**

Forking the project, but that takes a lot of time.

**Additional context**

None

**Comment by di** [comment]
Hi @matthewdeanmartin, thanks for the feature request!

I think we can add this (and make it additive like pip's [`--verbose` flag](https://pip.pypa.io/en/stable/cli/pip/?highlight=verbose#verbose)).

In the short term, you can also set `PIP_AUDIT_LOGLEVEL=debug` before running the command to get some additional output.

**Comment by woodruffw** [comment]
Yeah, making `--verbose` additive to bump the loglevel should be straightforward. In the meantime, `PIP_AUDIT_LOGLEVEL=debug` is indeed the best way to do it 🙂
