### ISSUE TITLE
Add a `conda` installation option for `pip-audit`

### ISSUE THREAD

**Issue by sugatoray** [trailofbits/pip-audit#199]
Adding a conda installation option could be helpful. I have started working on this already to make `pip-audit` available on `conda-forge` channel. Once the conda-forge :bulb: [**PR**](https://github.com/conda-forge/staged-recipes/pull/17235) gets merged, I will push a PR in this repository to update the install-instructions in the readme. 

```sh
conda install -c conda-forge pip-audit
```

- **Current status**: All CI's passed. Awaiting review/merger. https://github.com/conda-forge/staged-recipes/pull/17235
- **Note**: The PR is being used to add `pip-api` and `pip-audit` to conda-forge.

**Comment by woodruffw** [comment]
Cool, thank you for adding it! And yes, please open a PR to include it in the README 🙂

**Comment by woodruffw** [comment]
#200 will add a section for third-party packages; feel free to add it to that same section!

**Comment by sugatoray** [comment]
Sure. Will do.

**Comment by woodruffw** [comment]
I think this is all done 🙂
