### ISSUE TITLE
Raise an exception if vulnerabilities are found

### ISSUE THREAD

**Issue by threat-punter** [trailofbits/pip-audit#202]
Is it possible to raise an exception when `pip-audit` is executed and a vulnerability is found in one or more packages? Thanks in advance

**Comment by woodruffw** [comment]
Could you clarify what you mean by an "exception"?

`pip-audit` is currently meant to be run through the CLI, which doesn't have an exception mechanism in Unix-style shells. 

If you want to determine whether it's found any results, you can either use one of the machine readable output formats (like `--format=json`) and parse than, or check the exit code. For example, this is how you'd check the exit code in bash:

```bash
if pip-audit ; then
    echo "no vulnerabilities!"
else
    echo "some vulnerabilities!"
fi
```

(Also, just for the future: please use one of our issue templates! They perform automatic triage for us.)

**Comment by threat-punter** [comment]
Thanks for the quick response. Ah, perfect — I'll utilize the exit code.

> (Also, just for the future: please use one of our issue templates! They perform automatic triage for us.)

Noted. Cheers

**Comment by woodruffw** [comment]
Happy to help! Let us know if you have any other issues 🙂
