### ISSUE TITLE
pip-audit has unhealthy dependencies

### ISSUE THREAD

**Issue by fniessink** [trailofbits/pip-audit#203]
## Bug description

Running [Deadpendency](https://deadpendency.com) on pip-audit results in three unhealthy pip-audit (direct/indirect) dependencies:

- lockfile – 📦
  - ❌ Last package release over 24 months ago. Last release: 2015-11-25
  - ⚠ A source repository was not identified.
- requirements-parser – 📖 📦
  - ❌ No commits within the last 18 months. Last commit: 2020-03-31
  - ❌ Last package release over 24 months ago. Last release: 2018-01-12
- webencodings – 📖 📦
  - ❌ No commits within the last 18 months.
  - ❌ Last package release over 24 months ago. Last release: 2017-04-05

## Reproduction steps 

[Install Deadpendency](https://deadpendency.com/docs/getting-started#installation) on a public GitHub repo that has pip-audit in its requirements.txt. 

An example Deadpendency report (including the dependencies listed above) can be found here: https://github.com/ICTU/quality-time/pull/3021/checks?check_run_id=4501775840

## Expected behavior

pip-audit shouldn't rely on unhealthy dependencies.

## Platform information

* OS name and version: n/a
* `pip-audit` version (`pip-audit -V`): pip-audit 1.1.1
* Python version (`python -V` or `python3 -V`): Python 3.10.0
* `pip` version (`pip -V` or `pip3 -V`): pip 21.3.1

**Comment by di** [comment]
The `lockfile` project does appear to be deprecated based on https://pypi.org/project/lockfile/#description, which also provides alternatives.

The other two are subdependencies of active dependencies though, I'm not sure there's anything we can do there. Issues like this should probably be reported upstream in those projects instead.

I'll leave this open to investigate replacing `lockfile`.

**Comment by woodruffw** [comment]
Took a quick look, and I'm not 100% sure why we even depend on `lockfile` -- it might be a vestige of an earlier approach to reusing `pip`'s cache.

I'll try to remove it and see if anything explodes. If all is fine, I'll make a PR and close this out.

**Comment by woodruffw** [comment]
Okay, it's a secret transitive dependency of `CacheControl`. That also means we can't meaningfully replace it until `CacheControl` allows for an alternative implementation.
