### ISSUE TITLE
Make `pip-audit`'s spinner still more responsive

### ISSUE THREAD

**Issue by woodruffw** [trailofbits/pip-audit#227]
This is not triaged/prioritized since it's just a braindump.

#56 and #89 made `pip-audit` more responsive, but we can still do better.

In particular, the spinner still pauses when `pip-audit` is performing any kind of subprocess (i.e., calling out to `pip` internally).

We can probably improve this by adding some kind of synchronous monitoring of each subprocess -- we can either update the spinner naively (i.e., on a cadence, once every `X` milliseconds while waiting for the subprocess to terminate), or by monitoring the process's output and updating the spinner e.g. each time we see a new line on `stdout` or `stderr`.

Upsides:

* The `pip-audit` CLI becomes even more responsive, particularly in subprocess-heavy modes like `-r` and `--fix`

Downsides:

* We probably have to use one of the messier `subprocess` APIs, like `subprocess.communicate`

**Comment by di** [comment]
> or by monitoring the process's output and updating the spinner e.g. each time we see a new line on `stdout` or `stderr`.

I like this idea. It gives the user more feedback than a spinner that's just spinning every `X` ms because if `pip` hangs for some reason, the spinner hangs as well.

**Comment by woodruffw** [comment]
Taking a stab at this today.
