### ISSUE TITLE
Add a `RequirementSource` to our dependency source API.

### ISSUE THREAD

**Issue by woodruffw** [trailofbits/pip-audit#23]
#22 will implement `DependencySource` for `pip list`; we need a corresponding implementation for parsing and concretizing requirement files.

**Comment by woodruffw** [comment]
This is going to depend on a few different issues:

* #29 and #31 to select the right dependency/dependencies to use for expanding the dep tree
* Wrapping up #1, i.e. completing support for environment markers

**Comment by tetsuo-cpp** [comment]
I suspect that #44 will be merged shortly so I will work off that branch.
