### ISSUE TITLE
Explicitly ignore certain PYSECs

### ISSUE THREAD

**Issue by Elkasitu** [trailofbits/pip-audit#245]
**Is your feature request related to a problem? Please describe.**

Certain libraries have unfixed PYSECs that are acknowledged yet not a problem in certain scenarios.

For example, there is [PYSEC-2017-49](https://github.com/pypa/advisory-database/blob/main/vulns/kerberos/PYSEC-2017-49.yaml) for the kerberos library, however the function impacted by said PYSEC is already [documented](https://github.com/apple/ccs-pykerberos/blob/master/pysrc/kerberos.py#L52-L54) to be dangerous by the lib maintainers, and essentially if your application doesn't use said function it's not impacted.

**Describe the solution you'd like**

A flag like `--ignore` and/or a config file wherein PYSECs to be ignored can be defined, akin to how pylint and flake8 do it, this would allow people to more easily integrate the tool with CI/CD pipelines as any detected vulnerability currently triggers a non-zero exit-code

**Describe alternatives you've considered**

None

**Additional context**

None

**Comment by di** [comment]
Thanks for the issue! See also #209. This may be a better approach than just ignoring entire projects.

**Comment by Elkasitu** [comment]
@di actually I think both issues are valid, I checked #209 before writing this issue because #209 also applies to us as we have in-house libraries that we don't deploy to PyPI or any other public repository, and for which there will never be any public advisories.
