### ISSUE TITLE
Add a progress indicator to the CLI

### ISSUE THREAD

**Issue by woodruffw** [trailofbits/pip-audit#28]
When running `pip-audit` against a large environment or requirements file, querying the vulnerability service can take a decent amount of time. We should consider adding some sort of progress spinner or bar to the CLI so that the user knows that `pip-audit` hasn't hung or frozen.

Some considerations:

* We should only render the progress indicator if we know for certain that we're on a TTY
* The progress indicator's output **must not** interfere with the contents of `stdout`

**Comment by woodruffw** [comment]
https://github.com/tqdm/tqdm seems to be a popular progress bar module.

**Comment by di** [comment]
Let's use whatever pip uses here.

**Comment by woodruffw** [comment]
Looks like `pip` vendors the `progress` module: https://github.com/pypa/pip/tree/main/src/pip/_vendor/progress

Which is also here: https://github.com/verigak/progress

So we can use that as a dependency, and stick to a version that `pip` is already using to be certain that we're not incompatible during any future merge.

**Comment by woodruffw** [comment]
Thinking about this a bit more made me realize that we want to make the auditor and vulnerability service interfaces more accommodating to this: both should return iterators instead of concrete list/map types so that we can place the progress bar in the CLI rather than breaking our abstraction and putting it somewhere in the API.

**Comment by woodruffw** [comment]
I pushed up two concepts here:

* https://github.com/trailofbits/pip-audit/tree/ww/progress-progress (`progress`-based)
* https://github.com/trailofbits/pip-audit/tree/ww/tqdm-progress (`tqdm`-based)

We *probably* still want to just go with `progress`, but I wanted to highlight how relatively bare-bones it is. But it's a pretty simple module, so we might be able to subclass `Spinner` and add more context to it.

**Comment by woodruffw** [comment]
#40 addresses this with a custom `progress.spinner.Spinner` subclass for now.
