### ISSUE TITLE
Fails with stacktrace when caching is disabled

### ISSUE THREAD

**Issue by plannigan** [trailofbits/pip-audit#289]
## Bug description

In a docker image I have pip caching disabled to reduce the file image size. Running `pip-audit` with this set causes it to fail with a stack trace.

## Reproduction steps

* Disable caching by setting , `PIP_NO_CACHE_DIR` is to 'false'
* run `pip-audit -r requirements.txt`

Clearing the environment variable allows `pip-audit` to execute as expected.

## Expected behavior

I expect `pip-audit` to be able to still provide audit results when caching is disabled. If caching is a hard requirement for `pip-audit` to work, then I would expect a clear error message without a stack trace.

Based on the following part of the stack trace, I suspect caching is not a hard requirement.

```
  File "/pyenv/versions/3.9.5/envs/audit/lib/python3.9/site-packages/pip_audit/_cache.py", line 57, in _get_cache_dir
    pip_cache_dir = _get_pip_cache() if _PIP_VERSION >= _MINIMUM_PIP_VERSION else None
```

## Screenshots and logs

```
$  pip-audit -r requirements.txt
Traceback (most recent call last):
  File "/pyenv/versions/3.9.5/envs/audit/lib/python3.9/site-packages/pip_audit/_cache.py", line 37, in _get_pip_cache
    process = subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL)
  File "/pyenv/versions/3.9.5/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/pyenv/versions/3.9.5/envs/audit/bin/python3.9', '-m', 'pip', 'cache', 'dir']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/pyenv/versions/audit/bin/pip-audit", line 8, in <module>
    sys.exit(audit())
  File "/pyenv/versions/3.9.5/envs/audit/lib/python3.9/site-packages/pip_audit/_cli.py", line 374, in audit
    ResolveLibResolver(
  File "/pyenv/versions/3.9.5/envs/audit/lib/python3.9/site-packages/pip_audit/_dependency_source/resolvelib/resolvelib.py", line 54, in __init__
    self.provider = PyPIProvider(index_urls, timeout, cache_dir, state)
  File "/pyenv/versions/3.9.5/envs/audit/lib/python3.9/site-packages/pip_audit/_dependency_source/resolvelib/pypi_provider.py", line 283, in __init__
    self.session = caching_session(cache_dir, use_pip=True)
  File "/pyenv/versions/3.9.5/envs/audit/lib/python3.9/site-packages/pip_audit/_cache.py", line 150, in caching_session
    requests.Session(), cache=_SafeFileCache(_get_cache_dir(cache_dir, use_pip=use_pip))
  File "/pyenv/versions/3.9.5/envs/audit/lib/python3.9/site-packages/pip_audit/_cache.py", line 57, in _get_cache_dir
    pip_cache_dir = _get_pip_cache() if _PIP_VERSION >= _MINIMUM_PIP_VERSION else None
  File "/pyenv/versions/3.9.5/envs/audit/lib/python3.9/site-packages/pip_audit/_cache.py", line 39, in _get_pip_cache
    raise ServiceError(f"Failed to query the `pip` HTTP cache directory: {cmd}") from cpe
pip_audit._service.interface.ServiceError: Failed to query the `pip` HTTP cache directory: ['/pyenv/versions/3.9.5/envs/audit/bin/python3.9', '-m', 'pip', 'cache', 'dir']

$ pip config debug
env_var:
  PIP_EXTRA_INDEX_URL=''
  PIP_INDEX='https://artifactory.******.com/artifactory/api/pypi/python/simple'
  PIP_INDEX_URL='https://artifactory.******.com/artifactory/api/pypi/python/simple'
  PIP_NO_CACHE_DIR='false'
env:
global:
  /etc/xdg/pip/pip.conf, exists: False
  /etc/pip.conf, exists: False
site:
  /pyenv/versions/3.9.5/envs/audit/pip.conf, exists: False
user:
  /home/gunicorn/.pip/pip.conf, exists: False
  /home/gunicorn/.config/pip/pip.conf, exists: False
```

## Platform information

* OS name and version: CentOS 7.6
* `pip-audit` version (`pip-audit -V`):p ip-audit 2.3.1
* Python version (`python -V` or `python3 -V`): Python 3.9.5
* `pip` version (`pip -V` or `pip3 -V`): pip 21.1.1

**Comment by woodruffw** [comment]
> Based on the following part of the stack trace, I suspect caching is not a hard requirement.

Indeed it's not. We should guard the `pip` subprocess call, as well as respect `PIP_NO_CACHE_DIR`.

That being said, `PIP_NO_CACHE_DIR='false'` is a double negative. You probably meant `PIP_NO_CACHE_DIR='true'` (and it probably coincidentally works because `pip` only checks for the variable's presence).

**Comment by woodruffw** [comment]
(Also, thanks for reporting!)

In the mean time, you can pass a custom cache directory into `pip-audit` to work around the bug. I'll have a fix PR ready in a moment.

**Comment by woodruffw** [comment]
@plannigan could you give the changes in #290 a try, and let me know if they fix the issue for you?

**Comment by plannigan** [comment]
I tried that branch and it does work as expected!

Also, yes, it is a double negative. But is is also [valid](https://pip.pypa.io/en/stable/topics/configuration/#boolean-options). I swear I saw a PR that made it so that "true" also works now, but I can't find it now. I know very old versions of pip require false. I should check to see if I can change this now that 3.6 is EOL.
