### ISSUE TITLE
[Documentation] Possible JSON Format Output Alternative

### ISSUE THREAD

**Issue by MarkMoretto** [trailofbits/pip-audit#303]
**Is your feature request related to a problem? Please describe.**

Not everyone may have `jq` installed on their system.

**Describe the solution you'd like**

The PyPi [documentation](https://pypi.org/project/pip-audit/) for pip-audit has the following about midway down:

**Audit dependencies in JSON format**:

`$ pip-audit -f json | jq`

An alternative that could be used in the demo would be [json.tool](https://docs.python.org/3/library/json.html#module-json.tool) from the standard library, which is a good, cross-platform option:

`$ pip-audit -f json | python -m json.tool`

**Describe alternatives you've considered**

None

**Additional context**

None

**Comment by woodruffw** [comment]
#304 rolls up a bunch of README improvements, including this. Thanks again!
