### ISSUE TITLE
Pre-commit boilerplate: invalid version

### ISSUE THREAD

**Issue by jamesbraza** [trailofbits/pip-audit#326]
## Bug description

When using the README's currently suggested `pre-commit` string:

```yaml
  - repo: https://github.com/trailofbits/pip-audit
    rev: v2.1.2
    hooks:
      -   id: pip-audit
          args: ["-r", "requirements.txt"]
```

It doesn't work:

```
[INFO] Initializing environment for https://github.com/trailofbits/pip-audit.
An unexpected error has occurred: CalledProcessError: command: ('/usr/local/bin/git', 'checkout', 'v2.1.2')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    error: pathspec 'v2.1.2' did not match any file(s) known to git

Check the log at /Users/some.one/.cache/pre-commit/pre-commit.log
```

## Expected behavior

It should work, and to get it to work, change the `rev`:

```yaml
  - repo: https://github.com/trailofbits/pip-audit
    rev: v2.4.2
    hooks:
      -   id: pip-audit
          args: ["-r", "requirements.txt"]
```

## Platform information

n/a

**Comment by woodruffw** [comment]
Thanks for the report!

Yeah, I'm not sure why it has a nonexistent branch here. Ideally we'd update this `ref` automatically with each release...

cc @xsc27 for any thoughts on automating the above.

**Comment by woodruffw** [comment]
Oh, I see that it's in the README, not `.pre-commit-config.yaml`. We should be automatically updating both of those. Regardless, I'll have a manual fix PR ready in a moment.

**Comment by woodruffw** [comment]
#330 has the fixes.

**Comment by woodruffw** [comment]
Thanks again for reporting this @jamesbraza!
