### ISSUE TITLE
Use OSV 1.0 format

### ISSUE THREAD

**Issue by oliverchang** [trailofbits/pip-audit#38]
Hi!

I noticed that you're using the old OSV format fields in https://github.com/trailofbits/pip-audit/blob/b3fd732bf5f70311dcd9a32e15e26889597e3060/pip_audit/service/osv.py#L42.

This field is deprecated and will be removed soon, along with the top level "package" field. The new field which replaces this is "affect**ed**". Could you please use that instead? The 1.0 spec is described at https://ossf.github.io/osv-schema/.

**Comment by tetsuo-cpp** [comment]
My mistake. Thanks for letting us know @oliverchang. I'll fix that shortly.

**Comment by tetsuo-cpp** [comment]
@oliverchang 
I had a question about the new field. In `pip-audit`, we've been storing the affected versions as a list of ranges that consist of an introduced version and a fixed version.

In the new representation, it seems possible to have multiple consecutive "fixed' entries one after the other. When I was querying Django, I found one that looks like this:
```
          "ranges": [
            {
              "type": "ECOSYSTEM",
              "events": [
                {
                  "introduced": "0"
                },
                {
                  "fixed": "1.8"
                },
                {
                  "fixed": "1.8.16"
                },
                {
                  "introduced": "1.9"
                },
                {
                  "fixed": "1.9.11"
                },
                {
                  "introduced": "1.10"
                },
                {
                  "fixed": "1.10.3"
                }
              ]
            }
          ],
```
The NPM example in the format docs looks like [this](https://ossf.github.io/osv-schema/#npm-vulnerability-in-github-database) too. I was wondering, what does it mean for there to be two consecutive "fixed" events?

**Comment by oliverchang** [comment]
Thanks for pointing that out. It looks like a case of bad data, and even the [previous version](https://github.com/pypa/advisory-db/blob/fc80e7d00ed4ab4f059db2d7c2bd0b9fe22c6c38/vulns/django/PYSEC-2016-18.yaml) of this entry is inaccurate.

The evaluation algorithm is here: https://ossf.github.io/osv-schema/#evaluation. This would mean that: 
[0, 1.8) is affected, [1.9, 1.9.11) is affected, [1.10, 1.10.3) is affected but [1.8, 1.8.16) is unaffected, which seems redundant and wrong from the textual description. I'll fix this entry (and the misleading NPM example), but please let me know if you notice any similar ones.

**Comment by tetsuo-cpp** [comment]
Will do. Thanks @oliverchang.

One other thing I'm a bit unclear on is whether the objects in the "events" array are guaranteed to be in chronological order, or whether it just happens to be that way for most of the examples I've looked at.

The reason I ask is: for the purposes of `pip-audit`, when the tool flags a vulnerability in a dependency, I think it'd be helpful to give the user a set of version ranges so that the user can figure out what version they'd like to pin the dependency to to remediate the problem. So therefore, I'm trying to turn the "events" array into a series of ranges like what you described in your comment. I was wondering whether it's safe to assume a pattern like:
```
introduced
fixed
introduced
fixed
...
```

**Comment by oliverchang** [comment]
> One other thing I'm a bit unclear on is whether the objects in the "events" array are guaranteed to be in chronological order, or whether it just happens to be that way for most of the examples I've looked at.

It's not guaranteed. You'll need to sort them yourself.

> I think it'd be helpful to give the user a set of version ranges so that the user can figure out what version they'd like to pin the dependency to to remediate the problem. So therefore, I'm trying to turn the "events" array into a series of ranges like what you described in your comment. 

That sounds great! However, it completely necessary to include the "introduced" information? For a user to know which minimum version to pin to, it seems equally helpful to output something like:

```
Patched versions: 1.0.1, 2.1.2, 3.1.0
```

Which can just generated by extracting "fixed" events. Rather than:

```
Ranges: 
[1.0.0, 1.0.1)
[2.0.0, 2.1.2)
[3.0.0, 3.1.0)
```

**Comment by tetsuo-cpp** [comment]
I see what you mean. Usually, the user is just going to pin to the fix version so in most cases, the actual range isn't going to be super useful.

@woodruffw @di What do you think about changing the format to list a series of fix versions instead of ranges?

**Comment by woodruffw** [comment]
Thanks for bringing this to our attention @oliverchang! 

> What do you think about changing the format to list a series of fix versions instead of ranges?

Yeah, I think we should upgrade to the 1.0 format, and change our internal representation to individual fixed versions in the process. Ultimately, we probably want our upgrade advice to look like a greater-equal pin for the fixed version (e.g. `>= 1.2.3`), so we don't need the ranges at all.

**Comment by oliverchang** [comment]
Thanks a lot!
