### ISSUE TITLE
Output formats for `pip-audit`

### ISSUE THREAD

**Issue by woodruffw** [trailofbits/pip-audit#5]
Apart from supporting a standard SBOM format (#3), `pip-audit` should have at least two output formats for the MVP:

* A human-readable format for display on a terminal or logs
* A JSON format for interpretation by other programs

**Comment by tetsuo-cpp** [comment]
I imagine that this is going to look like:
```
class VulnerabilityFormat(ABC):
  def format(self, Dict[Dependency, List[Vulnerability]]) -> str:
    ...
```
And we can toggle via the CLI options similar to how we control vulnerability services.
