### ISSUE TITLE
Support filtering "system" dependencies

### ISSUE THREAD

**Issue by woodruffw** [trailofbits/pip-audit#7]
`pip_api.installed_distributions()` returns every visible distribution, which can potentially include distributions provided by the system/system package manager.

Issuing messages for these *might* not be desirable default behavior, for a few reasons:

* System-installed dependencies might be required by the system, and thus cannot be safely upgraded
* System-installed dependencies might be installed via a mechanism other than `pip`, so issued guidance might not always be applicable.
* System-installed dependencies might be patched by distribution maintainers to remove known vulnerabilities, without updating the version number.

As such, it probably makes sense for the CLI to have option(s) that allow the user to enable (or disable) filtering of dependencies that look like they're supplied by the system. This, in turn, requires us to come up with a reliable way of determining whether a given dependency is a "system" one.

**Comment by woodruffw** [comment]
(This is also only relevant when auditing a concrete set of dependencies e.g. via `pip list`, not when resolving dependencies via requirements file(s)).

**Comment by tetsuo-cpp** [comment]
I've been having a think about how this might look.

I think one way of doing might be to create an empty virtual environment and see what `pip-api` reports as being installed on it. We can consider these "system" packages and filter them out of the audit.

Not sure if there is a cleaner/more obvious way of achieving this.

> (This is also only relevant when auditing a concrete set of dependencies e.g. via pip list, not when resolving dependencies via requirements file(s)).

I think we might have to do this for requirements files too. Part of our dependency resolution involves installing source distributions and inspecting their packages via `pip list`, so this method suffers from the same pitfall.

**Comment by tetsuo-cpp** [comment]
Hmm, unless I'm misunderstanding something, I think the `-l` flag on `pip list` and `pip freeze` does what we want. It's shorthand for `--local` and refers to "if in a virtualenv that has global access, do not output globally-installed packages".

So I'd need to make a change to expose this functionality in `pip-api`.

@di Does this seem reasonable to you?

**Comment by tetsuo-cpp** [comment]
Opened https://github.com/di/pip-api/pull/103 to close the corresponding `pip-api` issue.
