### ISSUE TITLE
Implement `--fix` for `PipSource`

### ISSUE THREAD

**Issue by di** [trailofbits/pip-audit#82]
For each of the available inputs, support adding a `--fix` flag which will automatically update the dependency specification or environment in question to exclude any found vulnerabilities.

For example:

- if a vulnerability is found in a local environment, uninstall it and install a version with the fix
- if a vulnerability is found in a `requirements.txt` file, update the version specification for the affected project to exclude the vulnerable version

This should be a meta-issue for determining the UX around this feature, and we should create sub-issues for each of the potential ways a fix can be applied.

- [x] #212 
- [x] #215

**Comment by tetsuo-cpp** [comment]
I've opened #214 and #215 to track the remainder of this work. I'm going to repurpose this ticket to only capture the work for implementing `--fix` for `PipSource`.
