### ISSUE TITLE
Make the CLI *even more* responsive

### ISSUE THREAD

**Issue by woodruffw** [trailofbits/pip-audit#89]
Follow-up on #56, per https://github.com/trailofbits/pip-audit/pull/87#issuecomment-954320210:

> Regarding the feedback not being great at the beginning, in the future it might be worth reporting some extra state in the PyPIProvider. Something like:

> `Gathering metadata for sdist {name} ({version})`

**Comment by di** [comment]
I'd be in favor of this.
