### ISSUE TITLE
Maintain a CHANGELOG

### ISSUE THREAD

**Issue by woodruffw** [trailofbits/pip-audit#90]
Once we're prepared for a stable release series, we should begin a CHANGELOG.

**Comment by tetsuo-cpp** [comment]
I know some projects generate this programatically from commits or the GitHub PR history if that's something you're interested in.

**Comment by woodruffw** [comment]
Yeah, I have mixed feelings about those -- the projects that I've seen use them tend to not have well-curated CHANGELOGs, which defeats the point of having a CHANGELOG versus nice commit messages. 

I haven't used it before, but I think a good approach here might be a GitHub Actions check that requires a maintainer to "sign off" on each PR needing/not needing a CHANGELOG entry before approving it. That way it remains a manual process (and is curated), but there's a guardrail to prevent missing CHANGELOG entries. Thoughts?

**Comment by di** [comment]
Some projects (including `pip`) do this with https://pypi.org/project/towncrier/, but I think our changelog is simple enough here to just manually curate it for now.
