### ISSUE TITLE
Add an option to remove spinner feedback

### ISSUE THREAD

**Issue by tetsuo-cpp** [trailofbits/pip-audit#94]
I just realised that the feedback given by the `AuditSpinner` could be disruptive when trying to pipe the output to another program in a script. For example if you run something like:
```
$ pip-audit -r requirements.txt -f json | ./program-taking-json
```
Then the extra lines saying `Auditing <package>...` will cause problems. So we should add a flag to turn this feedback off so that it can be used in a scripting context.

Does that seem reasonable @woodruffw?

**Comment by woodruffw** [comment]
Hmm, I _thought_ that the `progress` module checked `isatty` before rendering the spinner. This might be a configuration mistake on my part, so I'll tackle it.

**Comment by tetsuo-cpp** [comment]
Oh, you're probably right. This was something I thought of, I didn't actually run into this problem myself.

**Comment by woodruffw** [comment]
Yeah, I wasn't able to cause buggy output on a TTY. Good thinking, though! We should open a separate issue for explicitly disabling the spinner even when a TTY is present, to accommodate users who have badly broken terminal emulators or simply prefer to not have a spinner. I'll create an issue for that.

**Comment by di** [comment]
FWIW, `pip` has a `--progress-bar` flag: https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-progress-bar
