### ISSUE TITLE
Allow users to explicitly disable the progress spinner

### ISSUE THREAD

**Issue by woodruffw** [trailofbits/pip-audit#96]
The spinner is enabled when `stderr` is a TTY by default. We should allow users to explicitly disable the spinner even when their standard error stream is going to a TTY, since not all TTYs behave well with line-pinned spinners and not all users may want a cute progress indicator at all.

**Comment by woodruffw** [comment]
To be specific: we should allow users to pass a flag like `--no-progress` to disable the spinner. There might also be an environment variable convention that we can/should respect, something like [`NO_COLOR`](https://no-color.org/) for ANSI colors.

**Comment by di** [comment]
FWIW, `pip` has a `--progress-bar` flag: https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-progress-bar

_Originally posted by @di in https://github.com/trailofbits/pip-audit/issues/94#issuecomment-956328748_
