### ISSUE TITLE
Output summary of results

### ISSUE THREAD

**Issue by di** [trailofbits/pip-audit#97]
When vulnerabilities are found, `pip-audit` should output something like "Found X known vulnerabilities in Y packages" or something similar in addition to the column/JSON output.

When no vulnerabilities are found, `pip-audit` should output something like "No known vulnerabilities found". I _think_ this should also suppress the column headers for a cleaner output, but could be convinced otherwise.

This should not interfere with other applications ability to consume `pip-audit` output via stdout.

**Comment by woodruffw** [comment]
Sounds good!

We'll put those messages on `stderr` to avoid interfering with `pip-audit`'s consumability. 

I'm also +1 on suppressing the column headers when there are no vulnerabilities to report -- they don't add anything of value to the output and the JSON output is the intended machine-readable format, so suppressing them will hopefully dissuade people from attempting to parse them.

**Comment by tetsuo-cpp** [comment]
Let's remember to update the output in the README examples when we do this.
